# Generated by Django 2.2.2 on 2019-06-18 04:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtaildocs', '0010_document_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('frontpage_blurb', models.CharField(blank=True, max_length=255)),
                ('aircraft_make_model', models.CharField(max_length=200)),
                ('aircraft_tail_number', models.CharField(max_length=50)),
                ('aircraft_description', wagtail.core.fields.RichTextField(blank=True)),
                ('billing_wet_rate', models.CharField(blank=True, max_length=200)),
                ('billing_dry_rate', models.CharField(blank=True, max_length=200)),
                ('billing_last_updated', models.DateField(blank=True)),
                ('pilot_requirements', wagtail.core.fields.RichTextField(blank=True)),
                ('aircraft_images', wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(blank=True, default='', max_length=120, null=True)), ('description', wagtail.core.blocks.RichTextBlock(blank=True, default='', null=True))]))], blank=True)),
                ('frontpage_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AircraftPageDocumentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='aircraft.AircraftPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
