# Generated by Django 2.2.2 on 2019-06-18 04:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_blurb_header', models.CharField(max_length=255)),
                ('footer_blurb_text', wagtail.core.fields.RichTextField()),
                ('youtube_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=255)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('contact_address_map_link', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('copyright_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero_heading', models.CharField(blank=True, max_length=255)),
                ('hero_subheading', models.CharField(blank=True, max_length=255)),
                ('content', wagtail.core.fields.RichTextField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero_heading', models.CharField(blank=True, max_length=255)),
                ('hero_subheading', models.CharField(blank=True, max_length=255)),
                ('home_heading', models.CharField(blank=True, max_length=255)),
                ('home_content', wagtail.core.fields.RichTextField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
